const pokemones = [
  {
    id: 1,
    nombre: "Bulbasaur",
    tipo: ["Planta"],
    altura: 0.7,
    peso: 6.9,
    generacion: 1,
    hp: 45,
    ataque: 49,
    velocidad: 45,
    defensa: 49,
    habilidad: "Espesura",
    tieneEvolucion: true,
    evolucion: "Ivysaur",
    nivelEvolucion: 16,
    rareza: "Común",
    imagen: "./assets/img/bulbasaur.png",
    sonido: "./assets/sound/bulbasaur.mp3",
    shiny: true,
    imagenShiny: "./assets/img/bulbasaur-shiny.png",
  },
  {
    id: 6,
    nombre: "Charizard",
    tipo: ["Fuego", "Volador"],
    altura: 1.7,
    peso: 90.5,
    generacion: 1,
    hp: 78,
    ataque: 84,
    velocidad: 100,
    defensa: 78,
    habilidad: "Mar Llamas",
    tieneEvolucion: false,
    evolucion: null,
    nivelEvolucion: null,
    rareza: "Raro",
    imagen: "./assets/img/charizard.png",
    sonido: "./assets/sound/charizard.mp3",
    shiny: true,
    imagenShiny: "./assets/img/charizard-shiny.png",
  },
];

console.log(pokemones);
// export { bulbasaur, charizard };
