export const pokemones = [
  {
    id: 1,
    nombre: "Bulbasaur",
    tipo: ["Planta", "Veneno"],
    altura: 0.7,
    peso: 6.9,
    generacion: 1,
    hp: 45,
    ataque: 49,
    velocidad: 45,
    defensa: 49,
    habilidad: "Espesura",
    tieneEvolucion: true,
    evolucion: "Ivysaur",
    nivelEvolucion: 16,
    rareza: "Común",
    imagen: "./assets/img/bulbasaur.png",
    sonido: "./assets/sound/bulbasaur.mp3",
    shiny: true,
    imagenShiny: "./assets/img/bulbasaur-shiny.png",
  },

  {
    id: 4,
    nombre: "Charmander",
    tipo: ["Fuego"],
    altura: 0.6,
    peso: 8.5,
    generacion: 1,
    hp: 39,
    ataque: 52,
    velocidad: 65,
    defensa: 43,
    habilidad: "Mar Llamas",
    tieneEvolucion: true,
    evolucion: "Charmeleon",
    nivelEvolucion: 16,
    rareza: "Común",
    imagen: "./assets/img/charmander.png",
    sonido: "./assets/sound/charmander.mp3",
    shiny: true,
    imagenShiny: "./assets/img/charmander-shiny.png",
  },

  {
    id: 7,
    nombre: "Squirtle",
    tipo: ["Agua"],
    altura: 0.5,
    peso: 9.0,
    generacion: 1,
    hp: 44,
    ataque: 48,
    velocidad: 43,
    defensa: 65,
    habilidad: "Torrente",
    tieneEvolucion: true,
    evolucion: "Wartortle",
    nivelEvolucion: 16,
    rareza: "Común",
    imagen: "./assets/img/squirtle.png",
    sonido: "./assets/sound/squirtle.mp3",
    shiny: true,
    imagenShiny: "./assets/img/squirtle-shiny.png",
  },

  {
    id: 25,
    nombre: "Pikachu",
    tipo: ["Eléctrico"],
    altura: 0.4,
    peso: 6.0,
    generacion: 1,
    hp: 35,
    ataque: 55,
    velocidad: 90,
    defensa: 40,
    habilidad: "Eléctrógeno",
    tieneEvolucion: true,
    evolucion: "Raichu",
    nivelEvolucion: null,
    rareza: "Raro",
    imagen: "./assets/img/pikachu.png",
    sonido: "./assets/sound/pikachu.mp3",
    shiny: true,
    imagenShiny: "./assets/img/pikachu-shiny.png",
  },

  {
    id: 54,
    nombre: "Psyduck",
    tipo: ["Agua"],
    altura: 0.8,
    peso: 19.6,
    generacion: 1,
    hp: 50,
    ataque: 52,
    velocidad: 55,
    defensa: 48,
    habilidad: "Humedad",
    tieneEvolucion: true,
    evolucion: "Golduck",
    nivelEvolucion: 33,
    rareza: "Común",
    imagen: "./assets/img/psyduck.png",
    sonido: "./assets/sound/psyduck.mp3",
    shiny: true,
    imagenShiny: "./assets/img/psyduck-shiny.png",
  },

  {
    id: 104,
    nombre: "Cubone",
    tipo: ["Tierra"],
    altura: 0.4,
    peso: 6.5,
    generacion: 1,
    hp: 50,
    ataque: 50,
    velocidad: 35,
    defensa: 95,
    habilidad: "Cabeza Roca",
    tieneEvolucion: true,
    evolucion: "Marowak",
    nivelEvolucion: 28,
    rareza: "Poco común",
    imagen: "./assets/img/cubone.png",
    sonido: "./assets/sound/cubone.mp3",
    shiny: true,
    imagenShiny: "./assets/img/cubone-shiny.png",
  },

  {
    id: 133,
    nombre: "Eevee",
    tipo: ["Normal"],
    altura: 0.3,
    peso: 6.5,
    generacion: 1,
    hp: 55,
    ataque: 55,
    velocidad: 55,
    defensa: 50,
    habilidad: "Adaptabilidad",
    tieneEvolucion: true,
    evolucion: "Vaporeon",
    nivelEvolucion: null,
    rareza: "Raro",
    imagen: "./assets/img/eevee.png",
    sonido: "./assets/sound/eevee.mp3",
    shiny: true,
    imagenShiny: "./assets/img/eevee-shiny.png",
  },

  {
    id: 143,
    nombre: "Snorlax",
    tipo: ["Normal"],
    altura: 2.1,
    peso: 460.0,
    generacion: 1,
    hp: 160,
    ataque: 110,
    velocidad: 30,
    defensa: 65,
    habilidad: "Inmunidad",
    tieneEvolucion: false,
    evolucion: null,
    nivelEvolucion: null,
    rareza: "Raro",
    imagen: "./assets/img/snorlax.png",
    sonido: "./assets/sound/snorlax.mp3",
    shiny: true,
    imagenShiny: "./assets/img/snorlax-shiny.png",
  },

  {
    id: 150,
    nombre: "Mewtwo",
    tipo: ["Psíquico"],
    altura: 2.0,
    peso: 122.0,
    generacion: 1,
    hp: 106,
    ataque: 110,
    velocidad: 130,
    defensa: 90,
    habilidad: "Presión",
    tieneEvolucion: false,
    evolucion: null,
    nivelEvolucion: null,
    rareza: "Legendario",
    imagen: "./assets/img/mewtwo.png",
    sonido: "./assets/sound/mewtwo.mp3",
    shiny: true,
    imagenShiny: "./assets/img/mewtwo-shiny.png",
  },

  {
    id: 151,
    nombre: "Mew",
    tipo: ["Psíquico"],
    altura: 0.4,
    peso: 4.0,
    generacion: 1,
    hp: 100,
    ataque: 100,
    velocidad: 100,
    defensa: 100,
    habilidad: "Sincronía",
    tieneEvolucion: false,
    evolucion: null,
    nivelEvolucion: null,
    rareza: "Mítico",
    imagen: "./assets/img/mew.png",
    sonido: "./assets/sound/mew.mp3",
    shiny: true,
    imagenShiny: "./assets/img/mew-shiny.png",
  },
];
